[versions]
pluginyml = "0.6.0"
runtask = "2.1.0"
shadow = "8.1.1"

paper = "1.20.2-R0.1-SNAPSHOT"
configurate = "4.1.2"
bstats = "3.0.2"

commandapi = "9.2.0"
brigadier = "1.0.18"

[plugins]
pluginyml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

commandapi-core = { module = "dev.jorel:commandapi-bukkit-core", version.ref = "commandapi" }
commandapi-plugin = { module = "dev.jorel:commandapi-bukkit-plugin", version.ref = "commandapi" }
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
