name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build Plugin
        run: ./gradlew build --no-daemon

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v3
        with:
          name: CloudCore-Artifacts
          path: build/libs/CloudCore-*
          if-no-files-found: error

      - name: Publish to package registry
        env:
          GH_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
          GH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        run: ./gradlew publish --no-daemon -PgithubUsername=$GH_USERNAME -PgithubPassword=$GH_PASSWORD
